/*
THIS SCRIPT IS ABOUT:
 CREATING 
  DATABASE 
  TABLE
  USER
 GRANTING PRIVILEDGES
 INSERTING DATA
 UPDATING DATA
 REMOVING DATA
*/

CREATE DATABASE PCPB;
CREATE TABLE quadro_efetivo(
matricula VARCHAR(255) primary key,
nome VARCHAR(255),
sobrenome VARCHAR(255),
classe VARCHAR(255)
);

ALTER TABLE quadro_efetivo 
ADD id INT FIRST;

ALTER TABLE tabela_null
ADD coluna4 VARCHAR(255);

ALTER TABLE tabela_null
MODIFY COLUMN coluna4 INT NOT NULL; 

BACKUP DATABASE PCPB
TO DISK = './';

BACKUP DATABASE PCPB 
TO DISK = './'
WITH DIFFERENTIAL;

TRUNCATE quadro_efetivos
DROP DATABASE PCPB;
